language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - nightly

notifications:
  email: false

branches:
  only:
    - master

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
